-- 0011: 캐릭터 자산 플랫폼 — 채번(HT-###) 기반 이미지 레지스트리
--
-- 채번 규칙:
--   · num 은 identity 로 자동 발급(= 채번). 결번이 생겨도 재사용하지 않는다.
--   · code 는 num 에서 파생되는 생성 열('HT-' || 3자리 패딩) — 수정 불가, 영구 식별자.
--   · 리포 추출 자산(HT-001~105)은 시드에서 num 을 명시하고, 이후 업로드는 자동 채번.
-- 쓰기 정책: RLS 활성 + 읽기 정책만 둔다 → INSERT/UPDATE/DELETE 는 service_role 전용.

create table if not exists public.character_assets (
  num int generated by default as identity primary key,
  -- greatest(): lpad는 길이 초과 시 오른쪽을 잘라내므로(HT-1000→HT-100 충돌),
  -- 999 초과 시 자릿수가 자연 확장되도록 패딩 길이를 num 자릿수와 함께 잡는다.
  code text generated always as (
    'HT-' || lpad(num::text, greatest(3, length(num::text)), '0')
  ) stored,
  name text not null,
  "group" text not null check ("group" in ('man', 'otter', 'prop', 'scene', 'custom')),
  section text not null default '',
  char_label text not null default '',
  src text not null,
  width int,
  height int,
  tags text[] not null default '{}',
  origin text not null default 'upload' check (origin in ('repo', 'upload')),
  active boolean not null default true,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists character_assets_code_idx
  on public.character_assets (code);

alter table public.character_assets enable row level security;

-- 활성 자산만 공개 읽기(숨김 자산·관리자 메모는 익명 노출 금지).
-- 쓰기 정책은 만들지 않는다 → service_role만 가능. 관리 화면·/c 라우트는 service_role 사용.
drop policy if exists character_assets_public_read on public.character_assets;
create policy character_assets_public_read
  on public.character_assets for select using (active);

-- 업로드 자산 저장용 공개 버킷 (service_role로만 업로드)
insert into storage.buckets (id, name, public)
values ('characters', 'characters', true)
on conflict (id) do nothing;
