-- 0012: 캐릭터 자산 시드 — 시트 추출본 HT-001~HT-105 등록
-- (scripts/build-character-assets.mjs 가 생성한 src/data/characters.json 기준)
insert into public.character_assets
  (num, name, "group", section, char_label, src, width, height, tags, origin)
values
(1, '히어로 · 노트북 데스크', 'man', '히어로', '메이커', '/characters/HT-001.png', 476, 542, array['메이커','히어로']::text[], 'repo'),
(2, '정면', 'man', '턴어라운드', '메이커', '/characters/HT-002.png', 188, 332, array['메이커','턴어라운드']::text[], 'repo'),
(3, '3/4 좌', 'man', '턴어라운드', '메이커', '/characters/HT-003.png', 148, 330, array['메이커','턴어라운드']::text[], 'repo'),
(4, '측면', 'man', '턴어라운드', '메이커', '/characters/HT-004.png', 164, 338, array['메이커','턴어라운드']::text[], 'repo'),
(5, '후면', 'man', '턴어라운드', '메이커', '/characters/HT-005.png', 138, 330, array['메이커','턴어라운드']::text[], 'repo'),
(6, '기본', 'man', '표정', '메이커', '/characters/HT-006.png', 114, 148, array['메이커','표정']::text[], 'repo'),
(7, '웃음', 'man', '표정', '메이커', '/characters/HT-007.png', 108, 148, array['메이커','표정']::text[], 'repo'),
(8, '생각', 'man', '표정', '메이커', '/characters/HT-008.png', 112, 146, array['메이커','표정']::text[], 'repo'),
(9, '놀람', 'man', '표정', '메이커', '/characters/HT-009.png', 122, 148, array['메이커','표정']::text[], 'repo'),
(10, '집중', 'man', '표정', '메이커', '/characters/HT-010.png', 118, 148, array['메이커','표정']::text[], 'repo'),
(11, '기쁨', 'man', '표정', '메이커', '/characters/HT-011.png', 116, 154, array['메이커','표정']::text[], 'repo'),
(12, '고민', 'man', '표정', '메이커', '/characters/HT-012.png', 116, 148, array['메이커','표정']::text[], 'repo'),
(13, '피곤', 'man', '표정', '메이커', '/characters/HT-013.png', 142, 156, array['메이커','표정']::text[], 'repo'),
(14, '감사', 'man', '표정', '메이커', '/characters/HT-014.png', 128, 158, array['메이커','표정']::text[], 'repo'),
(15, '확신', 'man', '표정', '메이커', '/characters/HT-015.png', 136, 156, array['메이커','표정']::text[], 'repo'),
(16, '독서 시간', 'man', '상황 모션', '메이커', '/characters/HT-016.png', 320, 244, array['메이커','상황 모션']::text[], 'repo'),
(17, '노트 정리', 'man', '상황 모션', '메이커', '/characters/HT-017.png', 332, 260, array['메이커','상황 모션']::text[], 'repo'),
(18, '노트북 작업', 'man', '상황 모션', '메이커', '/characters/HT-018.png', 322, 256, array['메이커','상황 모션']::text[], 'repo'),
(19, '아이디어 떠올리기', 'man', '상황 모션', '메이커', '/characters/HT-019.png', 266, 246, array['메이커','상황 모션']::text[], 'repo'),
(20, '화이트보드 기획', 'man', '상황 모션', '메이커', '/characters/HT-020.png', 284, 284, array['메이커','상황 모션']::text[], 'repo'),
(21, '코딩 작업', 'man', '상황 모션', '메이커', '/characters/HT-021.png', 256, 244, array['메이커','상황 모션']::text[], 'repo'),
(22, '유튜브 녹화', 'man', '상황 모션', '메이커', '/characters/HT-022.png', 290, 268, array['메이커','상황 모션']::text[], 'repo'),
(23, '커피 한 잔', 'man', '상황 모션', '메이커', '/characters/HT-023.png', 280, 262, array['메이커','상황 모션']::text[], 'repo'),
(24, '산책 · 사색', 'man', '상황 모션', '메이커', '/characters/HT-024.png', 376, 260, array['메이커','상황 모션']::text[], 'repo'),
(25, '추천', 'man', '미니멀 라인', '메이커', '/characters/HT-025.png', 170, 160, array['메이커','미니멀 라인']::text[], 'repo'),
(26, '핵심', 'man', '미니멀 라인', '메이커', '/characters/HT-026.png', 148, 160, array['메이커','미니멀 라인']::text[], 'repo'),
(27, '생각 중', 'man', '미니멀 라인', '메이커', '/characters/HT-027.png', 146, 160, array['메이커','미니멀 라인']::text[], 'repo'),
(28, '작업 중', 'man', '미니멀 라인', '메이커', '/characters/HT-028.png', 154, 150, array['메이커','미니멀 라인']::text[], 'repo'),
(29, '독서 중', 'man', '미니멀 라인', '메이커', '/characters/HT-029.png', 140, 152, array['메이커','미니멀 라인']::text[], 'repo'),
(30, '성취', 'man', '미니멀 라인', '메이커', '/characters/HT-030.png', 166, 158, array['메이커','미니멀 라인']::text[], 'repo'),
(31, '안녕', 'man', '미니멀 라인', '메이커', '/characters/HT-031.png', 160, 160, array['메이커','미니멀 라인']::text[], 'repo'),
(32, '프로필', 'man', '미니멀 라인', '메이커', '/characters/HT-032.png', 216, 200, array['메이커','미니멀 라인']::text[], 'repo'),
(33, '노트북', 'prop', '소품(메이커)', '메이커', '/characters/HT-033.png', 154, 158, array['메이커','소품(메이커)']::text[], 'repo'),
(34, '머그컵', 'prop', '소품(메이커)', '메이커', '/characters/HT-034.png', 148, 120, array['메이커','소품(메이커)']::text[], 'repo'),
(35, '책', 'prop', '소품(메이커)', '메이커', '/characters/HT-035.png', 126, 130, array['메이커','소품(메이커)']::text[], 'repo'),
(36, '노트', 'prop', '소품(메이커)', '메이커', '/characters/HT-036.png', 112, 118, array['메이커','소품(메이커)']::text[], 'repo'),
(37, '백팩', 'prop', '소품(메이커)', '메이커', '/characters/HT-037.png', 124, 156, array['메이커','소품(메이커)']::text[], 'repo'),
(38, '카메라', 'prop', '소품(메이커)', '메이커', '/characters/HT-038.png', 118, 98, array['메이커','소품(메이커)']::text[], 'repo'),
(39, '키보드', 'prop', '소품(메이커)', '메이커', '/characters/HT-039.png', 192, 88, array['메이커','소품(메이커)']::text[], 'repo'),
(40, '식물', 'prop', '소품(메이커)', '메이커', '/characters/HT-040.png', 40, 136, array['메이커','소품(메이커)']::text[], 'repo'),
(41, '히어로 · 책 읽기', 'otter', '히어로', '오터', '/characters/HT-041.png', 426, 556, array['오터','히어로']::text[], 'repo'),
(42, '기본(행복)', 'otter', '표정', '오터', '/characters/HT-042.png', 160, 138, array['오터','표정']::text[], 'repo'),
(43, '활짝 웃음', 'otter', '표정', '오터', '/characters/HT-043.png', 148, 142, array['오터','표정']::text[], 'repo'),
(44, '신남', 'otter', '표정', '오터', '/characters/HT-044.png', 150, 144, array['오터','표정']::text[], 'repo'),
(45, '생각 집중', 'otter', '표정', '오터', '/characters/HT-045.png', 150, 136, array['오터','표정']::text[], 'repo'),
(46, '궁금함', 'otter', '표정', '오터', '/characters/HT-046.png', 154, 138, array['오터','표정']::text[], 'repo'),
(47, '우와', 'otter', '표정', '오터', '/characters/HT-047.png', 140, 142, array['오터','표정']::text[], 'repo'),
(48, '감동', 'otter', '표정', '오터', '/characters/HT-048.png', 146, 140, array['오터','표정']::text[], 'repo'),
(49, '의욕 충전', 'otter', '표정', '오터', '/characters/HT-049.png', 150, 136, array['오터','표정']::text[], 'repo'),
(50, '자신감', 'otter', '표정', '오터', '/characters/HT-050.png', 122, 134, array['오터','표정']::text[], 'repo'),
(51, '고민', 'otter', '표정', '오터', '/characters/HT-051.png', 122, 136, array['오터','표정']::text[], 'repo'),
(52, '피곤', 'otter', '표정', '오터', '/characters/HT-052.png', 138, 136, array['오터','표정']::text[], 'repo'),
(53, '졸림', 'otter', '표정', '오터', '/characters/HT-053.png', 118, 134, array['오터','표정']::text[], 'repo'),
(54, '당황', 'otter', '표정', '오터', '/characters/HT-054.png', 118, 136, array['오터','표정']::text[], 'repo'),
(55, '걱정', 'otter', '표정', '오터', '/characters/HT-055.png', 158, 134, array['오터','표정']::text[], 'repo'),
(56, '부끄러움', 'otter', '표정', '오터', '/characters/HT-056.png', 152, 140, array['오터','표정']::text[], 'repo'),
(57, '설렘', 'otter', '표정', '오터', '/characters/HT-057.png', 132, 136, array['오터','표정']::text[], 'repo'),
(58, '감사', 'otter', '표정', '오터', '/characters/HT-058.png', 128, 138, array['오터','표정']::text[], 'repo'),
(59, '감격', 'otter', '표정', '오터', '/characters/HT-059.png', 148, 138, array['오터','표정']::text[], 'repo'),
(60, '실망', 'otter', '표정', '오터', '/characters/HT-060.png', 126, 132, array['오터','표정']::text[], 'repo'),
(61, '지침', 'otter', '표정', '오터', '/characters/HT-061.png', 158, 134, array['오터','표정']::text[], 'repo'),
(62, '으쓱', 'otter', '표정', '오터', '/characters/HT-062.png', 128, 134, array['오터','표정']::text[], 'repo'),
(63, '정면', 'otter', '포즈 · 각도', '오터', '/characters/HT-063.png', 122, 160, array['오터','포즈 · 각도']::text[], 'repo'),
(64, '3/4 좌', 'otter', '포즈 · 각도', '오터', '/characters/HT-064.png', 114, 160, array['오터','포즈 · 각도']::text[], 'repo'),
(65, '좌측면', 'otter', '포즈 · 각도', '오터', '/characters/HT-065.png', 112, 160, array['오터','포즈 · 각도']::text[], 'repo'),
(66, '후면', 'otter', '포즈 · 각도', '오터', '/characters/HT-066.png', 116, 158, array['오터','포즈 · 각도']::text[], 'repo'),
(67, '우측면', 'otter', '포즈 · 각도', '오터', '/characters/HT-067.png', 114, 160, array['오터','포즈 · 각도']::text[], 'repo'),
(68, '3/4 우', 'otter', '포즈 · 각도', '오터', '/characters/HT-068.png', 108, 156, array['오터','포즈 · 각도']::text[], 'repo'),
(69, '책 읽기', 'otter', '포즈 · 각도', '오터', '/characters/HT-069.png', 160, 172, array['오터','포즈 · 각도']::text[], 'repo'),
(70, '노트 작성', 'otter', '포즈 · 각도', '오터', '/characters/HT-070.png', 160, 172, array['오터','포즈 · 각도']::text[], 'repo'),
(71, '아이디어', 'otter', '포즈 · 각도', '오터', '/characters/HT-071.png', 150, 192, array['오터','포즈 · 각도']::text[], 'repo'),
(72, '발표하기', 'otter', '포즈 · 각도', '오터', '/characters/HT-072.png', 172, 176, array['오터','포즈 · 각도']::text[], 'repo'),
(73, '응원', 'otter', '포즈 · 각도', '오터', '/characters/HT-073.png', 132, 172, array['오터','포즈 · 각도']::text[], 'repo'),
(74, '걷기', 'otter', '포즈 · 각도', '오터', '/characters/HT-074.png', 130, 170, array['오터','포즈 · 각도']::text[], 'repo'),
(75, '달리기', 'otter', '포즈 · 각도', '오터', '/characters/HT-075.png', 142, 172, array['오터','포즈 · 각도']::text[], 'repo'),
(76, '가방 착용', 'otter', '포즈 · 각도', '오터', '/characters/HT-076.png', 118, 172, array['오터','포즈 · 각도']::text[], 'repo'),
(77, '커피 한 잔', 'otter', '포즈 · 각도', '오터', '/characters/HT-077.png', 114, 166, array['오터','포즈 · 각도']::text[], 'repo'),
(78, '휴식', 'otter', '포즈 · 각도', '오터', '/characters/HT-078.png', 150, 168, array['오터','포즈 · 각도']::text[], 'repo'),
(79, '풀컬러', 'otter', '라인 스타일', '오터', '/characters/HT-079.png', 214, 322, array['오터','라인 스타일']::text[], 'repo'),
(80, '미니멀 라인', 'otter', '라인 스타일', '오터', '/characters/HT-080.png', 198, 274, array['오터','라인 스타일']::text[], 'repo'),
(81, '모노톤', 'otter', '라인 스타일', '오터', '/characters/HT-081.png', 198, 342, array['오터','라인 스타일']::text[], 'repo'),
(82, '화이트 라인', 'otter', '라인 스타일', '오터', '/characters/HT-082.png', 220, 316, array['오터','라인 스타일']::text[], 'repo'),
(83, '추천', 'otter', '미니멀 라인', '오터', '/characters/HT-083.png', 94, 112, array['오터','미니멀 라인']::text[], 'repo'),
(84, '핵심', 'otter', '미니멀 라인', '오터', '/characters/HT-084.png', 92, 112, array['오터','미니멀 라인']::text[], 'repo'),
(85, '생각 중', 'otter', '미니멀 라인', '오터', '/characters/HT-085.png', 100, 114, array['오터','미니멀 라인']::text[], 'repo'),
(86, '작업 중', 'otter', '미니멀 라인', '오터', '/characters/HT-086.png', 128, 116, array['오터','미니멀 라인']::text[], 'repo'),
(87, '독서 중', 'otter', '미니멀 라인', '오터', '/characters/HT-087.png', 112, 118, array['오터','미니멀 라인']::text[], 'repo'),
(88, '인사', 'otter', '미니멀 라인', '오터', '/characters/HT-088.png', 102, 126, array['오터','미니멀 라인']::text[], 'repo'),
(89, '파이팅', 'otter', '미니멀 라인', '오터', '/characters/HT-089.png', 138, 134, array['오터','미니멀 라인']::text[], 'repo'),
(90, 'OK', 'otter', '미니멀 라인', '오터', '/characters/HT-090.png', 74, 130, array['오터','미니멀 라인']::text[], 'repo'),
(91, '프로필', 'otter', '미니멀 라인', '오터', '/characters/HT-091.png', 118, 132, array['오터','미니멀 라인']::text[], 'repo'),
(92, '노트북', 'prop', '소품(오터)', '오터', '/characters/HT-092.png', 124, 102, array['오터','소품(오터)']::text[], 'repo'),
(93, '책', 'prop', '소품(오터)', '오터', '/characters/HT-093.png', 104, 98, array['오터','소품(오터)']::text[], 'repo'),
(94, '노트', 'prop', '소품(오터)', '오터', '/characters/HT-094.png', 110, 100, array['오터','소품(오터)']::text[], 'repo'),
(95, '펜', 'prop', '소품(오터)', '오터', '/characters/HT-095.png', 56, 94, array['오터','소품(오터)']::text[], 'repo'),
(96, '머그컵', 'prop', '소품(오터)', '오터', '/characters/HT-096.png', 90, 90, array['오터','소품(오터)']::text[], 'repo'),
(97, '카메라', 'prop', '소품(오터)', '오터', '/characters/HT-097.png', 106, 86, array['오터','소품(오터)']::text[], 'repo'),
(98, '백팩', 'prop', '소품(오터)', '오터', '/characters/HT-098.png', 100, 114, array['오터','소품(오터)']::text[], 'repo'),
(99, '식물', 'prop', '소품(오터)', '오터', '/characters/HT-099.png', 70, 124, array['오터','소품(오터)']::text[], 'repo'),
(100, '화이트보드', 'prop', '소품(오터)', '오터', '/characters/HT-100.png', 114, 98, array['오터','소품(오터)']::text[], 'repo'),
(101, '독서 시간', 'scene', '상황 일러스트', '오터', '/characters/HT-101.png', 192, 188, array['오터','상황 일러스트']::text[], 'repo'),
(102, '아이디어 회의', 'scene', '상황 일러스트', '오터', '/characters/HT-102.png', 230, 184, array['오터','상황 일러스트']::text[], 'repo'),
(103, '코딩 작업', 'scene', '상황 일러스트', '오터', '/characters/HT-103.png', 216, 186, array['오터','상황 일러스트']::text[], 'repo'),
(104, '자연 산책', 'scene', '상황 일러스트', '오터', '/characters/HT-104.png', 220, 184, array['오터','상황 일러스트']::text[], 'repo'),
(105, '카페 휴식', 'scene', '상황 일러스트', '오터', '/characters/HT-105.png', 196, 192, array['오터','상황 일러스트']::text[], 'repo')
on conflict (num) do update set
  name = excluded.name,
  "group" = excluded."group",
  section = excluded.section,
  char_label = excluded.char_label,
  src = excluded.src,
  width = excluded.width,
  height = excluded.height,
  tags = excluded.tags,
  updated_at = now();

-- 다음 채번이 시드 이후 번호부터 시작하도록 시퀀스 이동
select setval(pg_get_serial_sequence('public.character_assets', 'num'),
  greatest((select max(num) from public.character_assets), 105), true);
