-- 0012: 캐릭터 자산 시드 — 시트 추출본 HT-001~HT-105 등록
-- (scripts/build-character-assets.mjs 가 생성한 src/data/characters.json 기준 — Real-ESRGAN 초해상 파이프라인)
insert into public.character_assets
  (num, name, "group", section, char_label, src, width, height, tags, origin)
values
(1, '히어로 · 노트북 데스크', 'man', '히어로', '메이커', '/characters/HT-001.png', 476, 531, array['메이커','히어로']::text[], 'repo'),
(2, '정면', 'man', '턴어라운드', '메이커', '/characters/HT-002.png', 145, 330, array['메이커','턴어라운드']::text[], 'repo'),
(3, '3/4 좌', 'man', '턴어라운드', '메이커', '/characters/HT-003.png', 138, 331, array['메이커','턴어라운드']::text[], 'repo'),
(4, '측면', 'man', '턴어라운드', '메이커', '/characters/HT-004.png', 113, 331, array['메이커','턴어라운드']::text[], 'repo'),
(5, '후면', 'man', '턴어라운드', '메이커', '/characters/HT-005.png', 130, 330, array['메이커','턴어라운드']::text[], 'repo'),
(6, '기본', 'man', '표정', '메이커', '/characters/HT-006.png', 105, 139, array['메이커','표정']::text[], 'repo'),
(7, '웃음', 'man', '표정', '메이커', '/characters/HT-007.png', 104, 138, array['메이커','표정']::text[], 'repo'),
(8, '생각', 'man', '표정', '메이커', '/characters/HT-008.png', 111, 143, array['메이커','표정']::text[], 'repo'),
(9, '놀람', 'man', '표정', '메이커', '/characters/HT-009.png', 118, 139, array['메이커','표정']::text[], 'repo'),
(10, '집중', 'man', '표정', '메이커', '/characters/HT-010.png', 106, 136, array['메이커','표정']::text[], 'repo'),
(11, '기쁨', 'man', '표정', '메이커', '/characters/HT-011.png', 111, 148, array['메이커','표정']::text[], 'repo'),
(12, '고민', 'man', '표정', '메이커', '/characters/HT-012.png', 108, 147, array['메이커','표정']::text[], 'repo'),
(13, '피곤', 'man', '표정', '메이커', '/characters/HT-013.png', 135, 149, array['메이커','표정']::text[], 'repo'),
(14, '감사', 'man', '표정', '메이커', '/characters/HT-014.png', 120, 149, array['메이커','표정']::text[], 'repo'),
(15, '확신', 'man', '표정', '메이커', '/characters/HT-015.png', 128, 150, array['메이커','표정']::text[], 'repo'),
(16, '독서 시간', 'man', '상황 모션', '메이커', '/characters/HT-016.png', 316, 232, array['메이커','상황 모션']::text[], 'repo'),
(17, '노트 정리', 'man', '상황 모션', '메이커', '/characters/HT-017.png', 329, 255, array['메이커','상황 모션']::text[], 'repo'),
(18, '노트북 작업', 'man', '상황 모션', '메이커', '/characters/HT-018.png', 320, 245, array['메이커','상황 모션']::text[], 'repo'),
(19, '아이디어 떠올리기', 'man', '상황 모션', '메이커', '/characters/HT-019.png', 285, 237, array['메이커','상황 모션']::text[], 'repo'),
(20, '화이트보드 기획', 'man', '상황 모션', '메이커', '/characters/HT-020.png', 282, 262, array['메이커','상황 모션']::text[], 'repo'),
(21, '코딩 작업', 'man', '상황 모션', '메이커', '/characters/HT-021.png', 268, 237, array['메이커','상황 모션']::text[], 'repo'),
(22, '유튜브 녹화', 'man', '상황 모션', '메이커', '/characters/HT-022.png', 260, 258, array['메이커','상황 모션']::text[], 'repo'),
(23, '커피 한 잔', 'man', '상황 모션', '메이커', '/characters/HT-023.png', 263, 252, array['메이커','상황 모션']::text[], 'repo'),
(24, '산책 · 사색', 'man', '상황 모션', '메이커', '/characters/HT-024.png', 360, 252, array['메이커','상황 모션']::text[], 'repo'),
(25, '추천', 'man', '미니멀 라인', '메이커', '/characters/HT-025.png', 132, 154, array['메이커','미니멀 라인']::text[], 'repo'),
(26, '핵심', 'man', '미니멀 라인', '메이커', '/characters/HT-026.png', 135, 153, array['메이커','미니멀 라인']::text[], 'repo'),
(27, '생각 중', 'man', '미니멀 라인', '메이커', '/characters/HT-027.png', 138, 153, array['메이커','미니멀 라인']::text[], 'repo'),
(28, '작업 중', 'man', '미니멀 라인', '메이커', '/characters/HT-028.png', 146, 148, array['메이커','미니멀 라인']::text[], 'repo'),
(29, '독서 중', 'man', '미니멀 라인', '메이커', '/characters/HT-029.png', 126, 150, array['메이커','미니멀 라인']::text[], 'repo'),
(30, '성취', 'man', '미니멀 라인', '메이커', '/characters/HT-030.png', 124, 158, array['메이커','미니멀 라인']::text[], 'repo'),
(31, '안녕', 'man', '미니멀 라인', '메이커', '/characters/HT-031.png', 152, 160, array['메이커','미니멀 라인']::text[], 'repo'),
(32, '프로필', 'man', '미니멀 라인', '메이커', '/characters/HT-032.png', 150, 184, array['메이커','미니멀 라인']::text[], 'repo'),
(33, '노트북', 'prop', '소품(메이커)', '메이커', '/characters/HT-033.png', 153, 152, array['메이커','소품(메이커)']::text[], 'repo'),
(34, '머그컵', 'prop', '소품(메이커)', '메이커', '/characters/HT-034.png', 86, 99, array['메이커','소품(메이커)']::text[], 'repo'),
(35, '책', 'prop', '소품(메이커)', '메이커', '/characters/HT-035.png', 109, 127, array['메이커','소품(메이커)']::text[], 'repo'),
(36, '노트', 'prop', '소품(메이커)', '메이커', '/characters/HT-036.png', 102, 103, array['메이커','소품(메이커)']::text[], 'repo'),
(37, '백팩', 'prop', '소품(메이커)', '메이커', '/characters/HT-037.png', 100, 150, array['메이커','소품(메이커)']::text[], 'repo'),
(38, '카메라', 'prop', '소품(메이커)', '메이커', '/characters/HT-038.png', 104, 88, array['메이커','소품(메이커)']::text[], 'repo'),
(39, '키보드', 'prop', '소품(메이커)', '메이커', '/characters/HT-039.png', 160, 80, array['메이커','소품(메이커)']::text[], 'repo'),
(40, '식물', 'prop', '소품(메이커)', '메이커', '/characters/HT-040.png', 34, 135, array['메이커','소품(메이커)']::text[], 'repo'),
(41, '히어로 · 책 읽기', 'otter', '히어로', '오터', '/characters/HT-041.png', 387, 543, array['오터','히어로']::text[], 'repo'),
(42, '기본(행복)', 'otter', '표정', '오터', '/characters/HT-042.png', 125, 135, array['오터','표정']::text[], 'repo'),
(43, '활짝 웃음', 'otter', '표정', '오터', '/characters/HT-043.png', 148, 135, array['오터','표정']::text[], 'repo'),
(44, '신남', 'otter', '표정', '오터', '/characters/HT-044.png', 150, 139, array['오터','표정']::text[], 'repo'),
(45, '생각 집중', 'otter', '표정', '오터', '/characters/HT-045.png', 98, 134, array['오터','표정']::text[], 'repo'),
(46, '궁금함', 'otter', '표정', '오터', '/characters/HT-046.png', 106, 135, array['오터','표정']::text[], 'repo'),
(47, '우와', 'otter', '표정', '오터', '/characters/HT-047.png', 159, 135, array['오터','표정']::text[], 'repo'),
(48, '감동', 'otter', '표정', '오터', '/characters/HT-048.png', 137, 135, array['오터','표정']::text[], 'repo'),
(49, '의욕 충전', 'otter', '표정', '오터', '/characters/HT-049.png', 150, 130, array['오터','표정']::text[], 'repo'),
(50, '자신감', 'otter', '표정', '오터', '/characters/HT-050.png', 114, 130, array['오터','표정']::text[], 'repo'),
(51, '고민', 'otter', '표정', '오터', '/characters/HT-051.png', 119, 134, array['오터','표정']::text[], 'repo'),
(52, '피곤', 'otter', '표정', '오터', '/characters/HT-052.png', 137, 130, array['오터','표정']::text[], 'repo'),
(53, '졸림', 'otter', '표정', '오터', '/characters/HT-053.png', 114, 127, array['오터','표정']::text[], 'repo'),
(54, '당황', 'otter', '표정', '오터', '/characters/HT-054.png', 127, 131, array['오터','표정']::text[], 'repo'),
(55, '걱정', 'otter', '표정', '오터', '/characters/HT-055.png', 129, 130, array['오터','표정']::text[], 'repo'),
(56, '부끄러움', 'otter', '표정', '오터', '/characters/HT-056.png', 144, 130, array['오터','표정']::text[], 'repo'),
(57, '설렘', 'otter', '표정', '오터', '/characters/HT-057.png', 125, 131, array['오터','표정']::text[], 'repo'),
(58, '감사', 'otter', '표정', '오터', '/characters/HT-058.png', 120, 133, array['오터','표정']::text[], 'repo'),
(59, '감격', 'otter', '표정', '오터', '/characters/HT-059.png', 118, 134, array['오터','표정']::text[], 'repo'),
(60, '실망', 'otter', '표정', '오터', '/characters/HT-060.png', 117, 159, array['오터','표정']::text[], 'repo'),
(61, '지침', 'otter', '표정', '오터', '/characters/HT-061.png', 150, 129, array['오터','표정']::text[], 'repo'),
(62, '으쓱', 'otter', '표정', '오터', '/characters/HT-062.png', 124, 129, array['오터','표정']::text[], 'repo'),
(63, '정면', 'otter', '포즈 · 각도', '오터', '/characters/HT-063.png', 113, 155, array['오터','포즈 · 각도']::text[], 'repo'),
(64, '3/4 좌', 'otter', '포즈 · 각도', '오터', '/characters/HT-064.png', 111, 154, array['오터','포즈 · 각도']::text[], 'repo'),
(65, '좌측면', 'otter', '포즈 · 각도', '오터', '/characters/HT-065.png', 110, 153, array['오터','포즈 · 각도']::text[], 'repo'),
(66, '후면', 'otter', '포즈 · 각도', '오터', '/characters/HT-066.png', 113, 151, array['오터','포즈 · 각도']::text[], 'repo'),
(67, '우측면', 'otter', '포즈 · 각도', '오터', '/characters/HT-067.png', 114, 154, array['오터','포즈 · 각도']::text[], 'repo'),
(68, '3/4 우', 'otter', '포즈 · 각도', '오터', '/characters/HT-068.png', 106, 151, array['오터','포즈 · 각도']::text[], 'repo'),
(69, '책 읽기', 'otter', '포즈 · 각도', '오터', '/characters/HT-069.png', 151, 166, array['오터','포즈 · 각도']::text[], 'repo'),
(70, '노트 작성', 'otter', '포즈 · 각도', '오터', '/characters/HT-070.png', 159, 167, array['오터','포즈 · 각도']::text[], 'repo'),
(71, '아이디어', 'otter', '포즈 · 각도', '오터', '/characters/HT-071.png', 152, 186, array['오터','포즈 · 각도']::text[], 'repo'),
(72, '발표하기', 'otter', '포즈 · 각도', '오터', '/characters/HT-072.png', 170, 169, array['오터','포즈 · 각도']::text[], 'repo'),
(73, '응원', 'otter', '포즈 · 각도', '오터', '/characters/HT-073.png', 126, 164, array['오터','포즈 · 각도']::text[], 'repo'),
(74, '걷기', 'otter', '포즈 · 각도', '오터', '/characters/HT-074.png', 128, 167, array['오터','포즈 · 각도']::text[], 'repo'),
(75, '달리기', 'otter', '포즈 · 각도', '오터', '/characters/HT-075.png', 138, 169, array['오터','포즈 · 각도']::text[], 'repo'),
(76, '가방 착용', 'otter', '포즈 · 각도', '오터', '/characters/HT-076.png', 117, 169, array['오터','포즈 · 각도']::text[], 'repo'),
(77, '커피 한 잔', 'otter', '포즈 · 각도', '오터', '/characters/HT-077.png', 111, 162, array['오터','포즈 · 각도']::text[], 'repo'),
(78, '휴식', 'otter', '포즈 · 각도', '오터', '/characters/HT-078.png', 150, 162, array['오터','포즈 · 각도']::text[], 'repo'),
(79, '풀컬러', 'otter', '라인 스타일', '오터', '/characters/HT-079.png', 208, 319, array['오터','라인 스타일']::text[], 'repo'),
(80, '미니멀 라인', 'otter', '라인 스타일', '오터', '/characters/HT-080.png', 191, 269, array['오터','라인 스타일']::text[], 'repo'),
(81, '모노톤', 'otter', '라인 스타일', '오터', '/characters/HT-081.png', 190, 268, array['오터','라인 스타일']::text[], 'repo'),
(82, '화이트 라인', 'otter', '라인 스타일', '오터', '/characters/HT-082.png', 218, 310, array['오터','라인 스타일']::text[], 'repo'),
(83, '추천', 'otter', '미니멀 라인', '오터', '/characters/HT-083.png', 92, 110, array['오터','미니멀 라인']::text[], 'repo'),
(84, '핵심', 'otter', '미니멀 라인', '오터', '/characters/HT-084.png', 90, 110, array['오터','미니멀 라인']::text[], 'repo'),
(85, '생각 중', 'otter', '미니멀 라인', '오터', '/characters/HT-085.png', 97, 113, array['오터','미니멀 라인']::text[], 'repo'),
(86, '작업 중', 'otter', '미니멀 라인', '오터', '/characters/HT-086.png', 128, 114, array['오터','미니멀 라인']::text[], 'repo'),
(87, '독서 중', 'otter', '미니멀 라인', '오터', '/characters/HT-087.png', 110, 112, array['오터','미니멀 라인']::text[], 'repo'),
(88, '인사', 'otter', '미니멀 라인', '오터', '/characters/HT-088.png', 101, 125, array['오터','미니멀 라인']::text[], 'repo'),
(89, '파이팅', 'otter', '미니멀 라인', '오터', '/characters/HT-089.png', 100, 130, array['오터','미니멀 라인']::text[], 'repo'),
(90, 'OK', 'otter', '미니멀 라인', '오터', '/characters/HT-090.png', 66, 129, array['오터','미니멀 라인']::text[], 'repo'),
(91, '프로필', 'otter', '미니멀 라인', '오터', '/characters/HT-091.png', 117, 129, array['오터','미니멀 라인']::text[], 'repo'),
(92, '노트북', 'prop', '소품(오터)', '오터', '/characters/HT-092.png', 120, 97, array['오터','소품(오터)']::text[], 'repo'),
(93, '책', 'prop', '소품(오터)', '오터', '/characters/HT-093.png', 100, 96, array['오터','소품(오터)']::text[], 'repo'),
(94, '노트', 'prop', '소품(오터)', '오터', '/characters/HT-094.png', 100, 97, array['오터','소품(오터)']::text[], 'repo'),
(95, '펜', 'prop', '소품(오터)', '오터', '/characters/HT-095.png', 53, 93, array['오터','소품(오터)']::text[], 'repo'),
(96, '머그컵', 'prop', '소품(오터)', '오터', '/characters/HT-096.png', 85, 85, array['오터','소품(오터)']::text[], 'repo'),
(97, '카메라', 'prop', '소품(오터)', '오터', '/characters/HT-097.png', 99, 83, array['오터','소품(오터)']::text[], 'repo'),
(98, '백팩', 'prop', '소품(오터)', '오터', '/characters/HT-098.png', 93, 110, array['오터','소품(오터)']::text[], 'repo'),
(99, '식물', 'prop', '소품(오터)', '오터', '/characters/HT-099.png', 68, 123, array['오터','소품(오터)']::text[], 'repo'),
(100, '화이트보드', 'prop', '소품(오터)', '오터', '/characters/HT-100.png', 114, 92, array['오터','소품(오터)']::text[], 'repo'),
(101, '독서 시간', 'scene', '상황 일러스트', '오터', '/characters/HT-101.png', 191, 186, array['오터','상황 일러스트']::text[], 'repo'),
(102, '아이디어 회의', 'scene', '상황 일러스트', '오터', '/characters/HT-102.png', 196, 179, array['오터','상황 일러스트']::text[], 'repo'),
(103, '코딩 작업', 'scene', '상황 일러스트', '오터', '/characters/HT-103.png', 216, 177, array['오터','상황 일러스트']::text[], 'repo'),
(104, '자연 산책', 'scene', '상황 일러스트', '오터', '/characters/HT-104.png', 214, 179, array['오터','상황 일러스트']::text[], 'repo'),
(105, '카페 휴식', 'scene', '상황 일러스트', '오터', '/characters/HT-105.png', 193, 185, array['오터','상황 일러스트']::text[], 'repo')
on conflict (num) do update set
  name = excluded.name,
  "group" = excluded."group",
  section = excluded.section,
  char_label = excluded.char_label,
  src = excluded.src,
  width = excluded.width,
  height = excluded.height,
  tags = excluded.tags,
  updated_at = now();

select setval(pg_get_serial_sequence('public.character_assets', 'num'),
  greatest((select max(num) from public.character_assets), 105), true);
